name: task
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4

dev_dependencies:
  animate_do: ^2.1.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  build_runner: ^2.3.2
  cloud_firestore: ^4.0.5
  dropdown_search: ^5.0.3
  equatable: ^2.0.5
  image_pickers: ^2.0.0+2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.5
  flutter_lints: ^2.0.0
  flutter_styled_toast: ^2.1.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  json_serializable: ^6.5.4
  lottie: null
  shared_preferences: ^2.0.15

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
